<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Code Coverage for <?php echo $file_path ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/jquery.min.js" type="text/javascript"></script>
    <script src="js/bootstrap.min.js" type="text/javascript"></script>
    <![endif]-->
</head>
<body>
<header>
    <div class="container">
        <div class="row">
            <div class="span12">
                <ul class="breadcrumb">
                    <li>
                        <a href="<?php echo $breads[0] . "/../index.html"; ?>">Home</a> <span class="divider">/</span>
                    </li>
                    <?php
                    foreach ($breads as $path_seg) {
                        if (empty($path_seg)) {
                            continue;
                        }
                        $pathesp[] = $path_seg;
                        $seg_name = implode("_", $pathesp) . ".html";

                        if (1 == 1) {
                            ?>
                            <li>
                                <a href="<?php echo implode("_", $pathesp) . ".html" ?>"><?php echo $path_seg ?></a> <span
                                    class="divider">/</span></li>
                        <?php } else { ?>
                            <li><?php echo $path_seg ?><span
                                    class="divider">/</span></li>
                        <?php } ?>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </div>
</header>
<div class="container">

    <table class="table table-borderless table-condensed">
        <tbody>
        <?php foreach ($file_lines as $file_line => $line_content) {
            if (!isset($line_status[$file_line + 1])) {
                $class = "";
            } else if ($line_status[$file_line + 1] == 1) {
                $class = "success";
            } else if ($line_status[$file_line + 1] == -2) {
                $class = "warning";
            } else if ($line_status[$file_line + 1] == -1) {
                $class = "danger";
            }
            ?>
            <tr class="<?php echo $class; ?>">
                <td>
                    <div align="right"><a name="<?php echo $file_line ?>"></a><a
                            href="#<?php echo $file_line ?>"><?php echo $file_line ?></a></div>
                </td>
                <td class="codeLine"><?php
                    if ($encoding != "UTF-8") {
                        $line_content = htmlspecialchars(@iconv($encoding, "utf-8//IGNORE", $line_content), ENT_QUOTES, "utf-8");
                    }
                    echo $line_content;
                    ?></td>
            </tr>
        <?php
        }
        ?>

        </tbody>
    </table>
    <footer>
        <h4>Legend</h4>

        <p>
            <span class="danger"><strong>Dead</strong></span>
            <span class="warning"><strong></strong></span>
            <span class="success"><strong>Using</strong></span>
        </p>

        <p>
            <small>Generated by CodeCovergeSniffer</small>
        </p>
    </footer>
</div>
</body>
</html>
